### ISSUE TITLE
Where is the doc about  how to implement `inlinehook without Jailbreak`?

### ISSUE THREAD

**Issue by CodeLife2012** [jmpews/HookZz#11]
Try to read the design [doc](https://github.com/jmpews/HookZz/blob/master/docs/HookFrameworkDesign.md), but can't find anything about how to implement.

**Comment by jmpews** [comment]
Not yet, busy with other things. but the trick is solidify hook.

**Comment by CodeLife2012** [comment]
So it's work on an non jailbreak device but the doc is not updated? @jmpews

**Comment by jmpews** [comment]
it's a trick, but limited. can't use it to hook system function(i.e. only hook the macho file that you can control)
