### ISSUE TITLE
Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by H0meDev** [jmpews/HookZz#13]
编译基于HookZz的tweak的时候报错：
Undefined symbols for architecture arm64:
  "ZzBuildHook(void*, void*, void**, void (*)(_RegState*, _ThreadStack*, _CallStack*), void (*)(_RegState*, _ThreadStack*, _CallStack*), bool)"

分享一下解决办法，即给hookzz加上一个C函数声明：

#ifdef __cplusplus
extern "C" {
#endif //__cplusplus

// hookzz 函数列表

#ifdef __cplusplus
}
#endif //__cplusplus

**Comment by jmpews** [comment]
是的, 对于 `.cpp`  以及 `.mm` 的编译是需要加上这个的.
