### ISSUE TITLE
当前不支持x86&&x86_64平台？

### ISSUE THREAD

**Issue by kigkrazy** [jmpews/HookZz#14]

**Comment by jmpews** [comment]
是的

**Comment by jmpews** [comment]
@ualwayswithme 支持

**Comment by linjiansheng** [comment]
@jmpews x86 build failed, try replace #include "zzdefs.h" to #include "kitzz.h".
also 
writer-x86.h:36:9: error: unknown type name 'ZzAssemblerWriter'
