### ISSUE TITLE
在ubuntu环境下无法编译

### ISSUE THREAD

**Issue by ckis** [jmpews/HookZz#19]
在win环境下编译是没问题的
在ubuntu环境下 android.mk中使用wildcard从而导致路径指向错误 这个小CASE就不劳大神了
但在编译interceptor-template-arm64.S时 大量报错

development/libmy/src/platforms/backend-arm64/interceptor-template-arm64.S:26:2: error: invalid instruction
 stp q6, q7, [sp, #(6*16)]
 ^
development/libmy/src/platforms/backend-arm64/interceptor-template-arm64.S:27:2: error: invalid instruction
 stp q4, q5, [sp, #(4*16)]
 ^
development/libmy/src/platforms/backend-arm64/interceptor-template-arm64.S:28:2: error: invalid instruction
 stp q2, q3, [sp, #(2*16)]
 ^
..................................
以下省略

请问该如何解决呢？

我是准备放在安卓7.1.2源码环境下编译的 不知道有没有影响

**Comment by jmpews** [comment]
之前一直在 Windows 和 macOS 测试, 我一会找个 ubuntu 测试下.
