### ISSUE TITLE
可以对一个静态库.a里的函数Hook吗比起fishhook能hook同一个模块内的直直接绑定symbol吗

### ISSUE THREAD

**Issue by sevenuncler** [jmpews/HookZz#25]
如，librtmp.a里的函数；比起fishhook不能hook静态库函数和同一个模块内直接绑定的symbol，这个可以做到吗? 还是把printf的例子拷过来，怎么直接崩溃了？ 提示找不到image, libhookzz.dylib

**Comment by jmpews** [comment]
在没有特殊需求下, 仍然建议建议使用 `fishhook` , HookZz 可以让 `fishhook` 走 `HookZz` 的 `pre_call` 和 `post_call` 流程
