### ISSUE TITLE
can't hook libart.so

### ISSUE THREAD

**Issue by Awekbing** [jmpews/HookZz#27]
https://stackoverflow.com/questions/49875987/hookzz-libart-so-not-working

大佬，为什么不能hook libart.so中的函数啊，printf的这些可以 Android7.0 ，import export都不行
但是如果是自定义的so中的函数可以hook

**Comment by jmpews** [comment]
能发我一个测试demo嘛?

**Comment by Awekbing** [comment]
我发你邮箱了，大佬抽空帮忙看下

**Comment by jmpews** [comment]
好的, 我明天看.

**Comment by jmpews** [comment]
ok 我收到了.

2018-04-18 10:20 GMT+08:00 Awekbing <notifications@github.com>:

**Comment by Awekbing** [comment]
是什么问题引起的啊，是不是我的用法不对？

**Comment by jmpews** [comment]
你在 wechat group 里嘛?

**Comment by Awekbing** [comment]
不在    能否啦我一下哦   感谢

**Comment by jmpews** [comment]
test done, not my fault.

**Comment by mockchain** [comment]
How this be fixed？

**Comment by mockchain** [comment]
> 是什么问题引起的啊，是不是我的用法不对？

问下后来这个问题解决了吗

**Comment by mockchain** [comment]
> 是什么问题引起的啊，是不是我的用法不对？

可以把解决方案透露下吗？
