### ISSUE TITLE
Getting Started第三步的问题

### ISSUE THREAD

**Issue by wonderffee** [jmpews/HookZz#3]
https://jmpews.github.io/zzpp/getting-started/ 第三步的run script中有一行是：

/Users/jmpews/Desktop/SpiderZz/Pwntools/Darwin/bin/optool install -c load -p "@executable_path/test_hook_oc.dylib" -t ${EXECUTABLE_NAME}

这个SpiderZz/Pwntools/Darwin/bin/optool 似乎并没有说明从哪里来的，求详

**Comment by jmpews** [comment]
[optool](https://github.com/alexzielenski/optool) 额, 这个你自己指定一下路径就行了啊.
