### ISSUE TITLE
现在非越狱IOS设备可以做inlinehook吗？

### ISSUE THREAD

**Issue by 91he** [jmpews/HookZz#31]
我需要在APP内HOOK一些socket函数，fishhook在物理设备上不能满足需求。

**Comment by jmpews** [comment]
nope

**Comment by 91he** [comment]
那静态二进制插桩可行吗？

**Comment by 91he** [comment]
@jmpews 微信二维码已过期，麻烦更新下，非常感谢。PS：我对这个项目很感兴趣。

**Comment by jmpews** [comment]
静态二进制patch可以的, 正在更新, 最近事情比较多, 要不你先加下 wechat 我拉你进去吧.
