### ISSUE TITLE
Using HookZz and VirtualApp together.

### ISSUE THREAD

**Issue by jbro129** [jmpews/HookZz#33]
Hello, I want to use HookZz on an app that is located inside of the virtual space of a host app that use VirtualApp by asLody.  The main library I want to hook is located in /data/data/{Package Name}/virtual/data/app/{Package Name in Virtual Space}/lib/lib.so and not in /data/data/{Package Name}/lib/lib.so
How would I hook and possibly use ZzHookReplace when lib I want to hook is located in a different directory?  Does HookZz have an option to declare the lib location to hook?

Example of custom declaration of lib -> ZzHookLib(const char * filename, const char * mode FILE * stream );

Example of usage -> ZzHookLib("/data/data/com.example.example/lib/libgame.so", "w", stdout);
Example of usage with VirtualApp ->
ZzHookLib("/data/data/com.example.example/virtual/data/app/com.installed.example/lib/libgame.so", "w", stdout);

Or maybe you can use ZzHookReplace and add a parameter for the lib?

ZzHookReplace("/data/data/com.example.example/virtual/data/app/com.installed.example/lib/libgame.so", (void *) stuff_addr, (void *) fake_stuff, (void **) &orig_suff);

This is mostly just ideas I am hoping you can maybe implement.

**Comment by jmpews** [comment]
maybe you need GOT hook, AKA replace GOT symbol address.

**Comment by jbro129** [comment]
ZzHookGOT says it only support Darwin, but I am working with Arm.
