### ISSUE TITLE
怎样编译iOS armv7的版本？

### ISSUE THREAD

**Issue by qingda** [jmpews/HookZz#36]
cmake .. \
-DCMAKE_TOOLCHAIN_FILE=cmake/ios.toolchain.cmake \
-DIOS_PLATFORM=OS \
-DENABLE_VISIBILITY=ON \
-DIOS_ARCH=armv7 \
-DENABLE_ARC=TRUE \
-DENABLE_BITCODE=OFF \
-DCXX=OFF \
-DX_ARCH=armv7 \
-DX_PLATFORM=iOS \
-DX_SHARED=ON \
-DX_LOG=ON \
-DCMAKE_VERBOSE_MAKEFILE=OFF
make

我这样编译会有一个异常：
`/Users/aabbc/github/HookZz/src/thread_support/thread_local_storage.c:4:1: error: thread-local storage is not supported for the current target`

**Comment by qingda** [comment]
cmake .. 命令执行后输出以下内容
`-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: OS, architecture(s): armv7
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk for platform: OS
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 8.1 (SDK version: 11.4)
-- Version flags set to: -miphoneos-version-min=8.1
-- Disabling bitcode support.
-- Enabling ARC support.
-- Building with Xcode version: 9.4.1
-- Configuring iOS build for platform: OS, architecture(s): armv7
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using a data_ptr size of 4
-- Building for minimum iOS version: 8.1 (SDK version: 11.4)
-- Version flags set to: -miphoneos-version-min=8.1
-- Disabling bitcode support.
-- Enabling ARC support.
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- The ASM compiler identification is AppleClang
-- Found assembler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Detect Build Info
-- 	System: Darwin
-- 	Architecture: arm
-- [*] searching *.c from ./src
-- [*] searching *.c from ./src/std_kit
-- [*] searching *.c from ./src/thread_support
-- [*] searching *.c from ./src/compiler-rt/lib/builtins
-- [*] searching *.c from ./src/platforms/backend-posix
-- [*] searching *.c from ./src/platforms/backend-darwin
-- [*] searching *.S from ./src
-- [*] searching *.S from ./src/std_kit
-- [*] searching *.S from ./src/thread_support
-- [*] searching *.S from ./src/compiler-rt/lib/builtins
-- [*] searching *.S from ./src/platforms/backend-posix
-- [*] searching *.S from ./src/platforms/backend-darwin
-- [*] searching *.h from ./src
-- [*] searching *.h from ./src/std_kit
-- [*] searching *.h from ./src/thread_support
-- [*] searching *.h from ./src/compiler-rt/lib/builtins
-- [*] searching *.h from ./src/platforms/backend-posix
-- [*] searching *.h from ./src/platforms/backend-darwin
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/aabbc/github/HookZz/build`

**Comment by qingda** [comment]
cmake .. 命令执行后输出以下内容
`-- Building with Xcode version: 9.4.1

-- Configuring iOS build for platform: OS, architecture(s): armv7

-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk for platform: OS

-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang

-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++

-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool

-- Using a data_ptr size of 4

-- Building for minimum iOS version: 8.1 (SDK version: 11.4)

-- Version flags set to: -miphoneos-version-min=8.1

-- Disabling bitcode support.

-- Enabling ARC support.

-- Building with Xcode version: 9.4.1

-- Configuring iOS build for platform: OS, architecture(s): armv7

-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool

-- Using a data_ptr size of 4

-- Building for minimum iOS version: 8.1 (SDK version: 11.4)

-- Version flags set to: -miphoneos-version-min=8.1

-- Disabling bitcode support.

-- Enabling ARC support.

-- The C compiler identification is AppleClang 9.1.0.9020039

-- The CXX compiler identification is AppleClang 9.1.0.9020039

-- The ASM compiler identification is AppleClang

-- Found assembler: 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Detect Build Info

-- 	System: Darwin

-- 	Architecture: arm

-- [*] searching *.c from ./src

-- [*] searching *.c from ./src/std_kit

-- [*] searching *.c from ./src/thread_support

-- [*] searching *.c from ./src/compiler-rt/lib/builtins

-- [*] searching *.c from ./src/platforms/backend-posix

-- [*] searching *.c from ./src/platforms/backend-darwin

-- [*] searching *.S from ./src

-- [*] searching *.S from ./src/std_kit

-- [*] searching *.S from ./src/thread_support

-- [*] searching *.S from ./src/compiler-rt/lib/builtins

-- [*] searching *.S from ./src/platforms/backend-posix

-- [*] searching *.S from ./src/platforms/backend-darwin

-- [*] searching *.h from ./src

-- [*] searching *.h from ./src/std_kit

-- [*] searching *.h from ./src/thread_support

-- [*] searching *.h from ./src/compiler-rt/lib/builtins

-- [*] searching *.h from ./src/platforms/backend-posix

-- [*] searching *.h from ./src/platforms/backend-darwin

-- Configuring done

-- Generating done

-- Build files have been written to: /Users/aabbc/github/HookZz/build`

**Comment by jmpews** [comment]
try the lastest version ( v2 update done).

**Comment by No-Karma** [comment]
请教一下，是不是xcode11编译不了armv7？
参考1楼的写法，提示ios相关命令已经不存在了，简单改写了，不知道对不对，编译之后，只能获得lib.a文件，且是x86格式~一脸懵逼，如有打扰，十分抱歉~~
![1](https://user-images.githubusercontent.com/25654222/68453658-34295b00-0231-11ea-91b7-f9170216e3d3.png)

![2](https://user-images.githubusercontent.com/25654222/68453644-2b388980-0231-11ea-9071-4bb8c7a9cbc9.png)
![3](https://user-images.githubusercontent.com/25654222/68453650-2ecc1080-0231-11ea-8501-8e3d993ea515.png)
