### ISSUE TITLE
error

### ISSUE THREAD

**Issue by azureplus** [jmpews/HookZz#37]
/code/ios/HookZz/src/platforms/arch-arm64/arch-arm64.c:5:44: error: no member named 'general' in 'struct _RegState'
    void *next_hop_addr_PTR = (void *)&rs->general.regs.x15;
                                       ~~  ^
/code/ios/HookZz/src/platforms/arch-arm64/arch-arm64.c:10:39: error: no member named 'lr' in 'struct _RegState'
    void *ret_addr_PTR = (void *)&rs->lr;

**Comment by jmpews** [comment]
try the latest version (v2 update done)
