### ISSUE TITLE
lost free(interceptor) ?

### ISSUE THREAD

**Issue by enlangs** [jmpews/HookZz#4]
https://github.com/jmpews/HookZz/blob/116a834a2dda832c4d2b7d193d8c01da39b69c2b/src/interceptor.c#L38

**Comment by jmpews** [comment]
好像是的. 最近在主力开发(重构) `development` 分支, `master` 的 interceptor 没有写规范的 `destory` 函数.

**Comment by enlangs** [comment]
我给你个 PR 吧。

**Comment by enlangs** [comment]
其实你这种基于堆有好有坏。还需要考虑并发的问题。

**Comment by jmpews** [comment]
是这样的, `interceptor` 只是一个信息记录的 center, 这些都是在 `activate hook` 之前做的工作. 当正式开始走 `hook` 流程时, 不会涉及到对 `interceptor` 读写, 并且 `hookentry` 的地址是在构建 `trampoline` 的固化到 `trampoline` 里的. 所以在执行 `hook` 流程时, 不会涉及到 竞争/锁 的问题.

**Comment by enlangs** [comment]
我对这部分知识还不是很了解，我先消化下。  感谢！
