### ISSUE TITLE
Problem compiling the library with armeabi

### ISSUE THREAD

**Issue by ItalianApkDownloader** [jmpews/HookZz#41]
In file included from ././src/platforms/arch-arm/instructions.c:1:
././src/platforms/arch-arm/instructions.h:5:10: fatal error: 'zkit.h' file not found
#include "zkit.h"
         ^~~~~~~~
1 error generated.
make: *** [obj/local/armeabi/objs/hookzz/./src/platforms/arch-arm/instructions.o] Error 1

I cant find this file in the src folder

**Comment by jmpews** [comment]
try latest version (v2 update done)
